# =============================================================================
#                    Author: Florent TOURNOIS | License: MIT                   
# =============================================================================

# [pep8]
ignore = E302, W504